### ISSUE TITLE
Windows installation errors

### ISSUE THREAD

**Issue by Datinhkhach** [wms2/mywms#16]
I'm trying to install mywms on my personal computer but getting an error on the rich client installation step .

> Compiling 305 source files to C:\mywms\rich.client\los.clientsuite\LOS Common\build\classes
Ignoring source, target and bootclasspath as release has been set
C:\mywms\rich.client\los.clientsuite\LOS Common\src\de\linogistix\common\util\GraphicUtil.java:13: error: package com.sun.imageio.plugins.jpeg does not exist
import com.sun.imageio.plugins.jpeg.JPEGImageWriter;
1 error
C:\Program Files\NetBeans-12.4\netbeans\harness\suite.xml:163: The following error occurred while executing this line:
C:\Program Files\NetBeans-12.4\netbeans\harness\common.xml:207: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 16 seconds)

**Comment by Datinhkhach** [comment]
The **package com.sun.imageio.plugins.jpeg** no longer avaiable from java7 .

**Comment by Datinhkhach** [comment]
Check Error : **No dependent module org.apache.commons**
![2021-07-22_13-41-05](https://user-images.githubusercontent.com/86252906/126599579-5f0e8cfc-a81b-492d-af10-78676a8b739f.png)

**Comment by wms2** [comment]
Which java version/vendor do you use? In OpenJDK 11 the class com.sun.imageio.plugins.jpeg.JPEGImageWriter is part of the java runtime. 
Maybe that there are differences between java vendors.
I use OpenJDK 1.8 and OpenJDK 11 of Oracle Corporation. And there the package com.sun.imageio... is still included.

**Comment by wms2** [comment]
For the missing module you have to define a netbeans platform. Please have a look to the GettingStarted.pdf document. There is a description how to setup the client.
The screen should look line this:
![Screenshot_20210809_123046](https://user-images.githubusercontent.com/52384988/128698703-15686be5-09c4-4089-a1f6-115c22c0e60d.png)
