### ISSUE TITLE
How to translate the UI in any language

### ISSUE THREAD

**Issue by Datinhkhach** [wms2/mywms#17]
Hi

How can I translate interface of wms2 to another language?

Thank you!

**Comment by wms2** [comment]
For translation myWMS uses the java ResourceBundle.

Search in the file system of client and server application for *Bundle.properties files. There are about 30 bundles which have content. In each bundle add a new file with your language extension. The default language and the German language files are valid and can be used as a template for your translation.

Please have a look to the java documentation, stackoverflow or youtube tutorials of how to handle java resource bundles.
