### ISSUE TITLE
Could not resolve propertygoodsReceiptNumber

### ISSUE THREAD

**Issue by WPMillett** [wms2/mywms#21]
I received an error after completing the setup and attempting to work with a goods receipt in the mobile app.  I have worked with the old versions (1.6 & 1.8) and I started with a new installation of PostgreSql 11.
I downloaded release 2.8.0 and followed the instructions for using PostgreSql.  The client app runs despite a few warnings and the mobile app appears to function until this error throws me back to the menu. 
Here is part of the first line of the error:
Invocation failed on component QueryGoodsReceiptServiceBean for method public abstract java.util.List de.linogistix.los.inventory.service.QueryGoodsReceiptServiceRemote.getOpenDtoListByCode(java.lang.String,boolean,int,int): javax.ejb.EJBException: java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: goodsReceiptNumber of: de.wms2.mywms.goodsreceipt.GoodsReceipt [SELECT distinct new de.linogistix.los.inventory.service.dto.GoodsReceiptTO(gr.id, gr.goodsReceiptNumber, gr.forwarder, gr.deliveryNoteNumber) FROM de.wms2.mywms.goodsreceipt.GoodsReceipt gr  join gr.adviceLines adv WHERE ( gr.orderNumber like :code or gr.deliveryNoteNumber like :code or adv.externalNumber like :code or adv.orderNumber like :code or adv.itemData.number like :code or adv.itemData.id = ANY( select idn.itemData.id from de.wms2.mywms.product.ItemDataNumber idn where idn.number like :code) )  and gr.state>=:minState and gr.state<=:maxState ORDER BY gr.orderNumber]

**Comment by wms2** [comment]
Fixed with commit 13b4947

**Comment by WPMillett** [comment]
Thank you, sir.
