### ISSUE TITLE
Missing bestbefore from pickingorderline

### ISSUE THREAD

**Issue by Akjo4712** [wms2/mywms#22]
Hello! 

I am trying to make some Exports we previously had in MyWMS 1.8. There seems to be no proper way to determine which bestbefore date the picked Items have. Currently there is a pickedlotnumber but no pickedbestbefore Field in the Database.

As a workaround I am currently queriying for stockunits which are on the same Packet with the same Lotnumber and Itemnumber in order to extract the bestbefore from there. This query is kind of russian roulette as this query might select wrong stockunits in edge cases.

Can we save the pickedbestbefore in pickingorderline along with pickedlotnumber? I am unsure how to implement a new Field in the Database via Hibernate. Would appretiante if you could help out with this.

**Comment by Akjo4712** [comment]
By the way if I am missing something and there is a proper way to find the bestbefore date from a pickingorderline Row, please let me know.

**Comment by wms2** [comment]
Hello,
you find the picked stock units in the packets. The packets are
referenced by the pickingorder or deliveryorder.

With this you can query all stock units and bestbefore dates, which have
been taken for a picking- or deliveryorder.
And you are right, there is no direct unique reference between a single
pickingorder-line and the picked bestbefore date. But in my projects, I
did not have the need to know which line caused a specific bestbefore
date. I only needed to know which bestbefore-dates are used for the
complete picking- or deliveryorder.

It should be no problem to add and fill a new field in the
pickingorder-line.

Please give me a hint, in which use-case this information is needed.

**Comment by Akjo4712** [comment]
We have a Interface for Delivery Orders with our Customers. They send us the Order and Orderlines via API. After the Deliveryorder is completed, the Interface notifys the Customer of the finished Delivery Order and the delivered Bestbefore Dates based on the Orderline.

Our Customer now might Request in Line 1 to deliver X Pieces of Item A with no specific Bestbefore and in Line 2 Request Y Pieces of Item A with a specific Bestbefore. If they explicitly request a Bestbefore Date they can retrieve expired or nearly expired Products for delivery.

When the same item is included multiple Times in one Order I can not accurate determine which Bestbefore Dates where picked for which Orderline.

**Comment by wms2** [comment]
OK, we will add a new field with the picked bestbefore date to the pickingorderline.

**Comment by Akjo4712** [comment]
Nice. I think this one shouldn't be hard to implement. Basically we need 1 new Field in the Database as well as in the Object Model and set the pickedbestbefore Date exactly in the same spots as we set the pickedlotnumber. There should be no need for new logics and mechanics.

I have never added new Fields to MyWMS. If you can Point out things which need to be done, I would make the implementations and create a Merge Request.

**Comment by wms2** [comment]
Have a look to the last commit. I hope, it solves the problem.

Maybe the next time you are missing a field, you can make the 
implementation.

**Comment by Akjo4712** [comment]
Thanks for your help! If there is something more to add I am sure that I can add those Fields from now on.
