### ISSUE TITLE
Mark Intake without Order in inventoryjournal with own activitycode or recordtype

### ISSUE THREAD

**Issue by Akjo4712** [wms2/mywms#23]
With MyWMS 1.8 all Intakes without a Order where marked in the Table inventoryjournal with the activitycode "IMAN". Unfortunately it seems that the activitycode is empty for those Intakes with the current Version of MyWMS and it is not easy to distinguish between normal movement and intakes. As we have Reports/Exports which show all Goods-In, including normal Goods-In and Intakes without Orders/Avis.

**Comment by wms2** [comment]
Hello,

IMAN... was the activitycode for manual postings. This has been removed. 
All other postings use still an order number as activity code.

In your reports you can replace IMAN with an empty value.

**Comment by Akjo4712** [comment]
Hi! Thanks for your reply. I have already adopted the Reports acording to your advice.
