### ISSUE TITLE
Printer not found. name=

### ISSUE THREAD

**Issue by montymotz** [wms2/mywms#3]
Hi,

how i print with myWMS?

Printing with `# lpr -P OKIDRUCKER test.txt` runs finely under command line.

When i set the System variable in myWMS, log says:

14:33:36,497 INFO  [de.linogistix.los.common.businessservice.LOSPrintServiceBean] (default task-1) Printer not found. name=OKIDRUCKER

![1](https://user-images.githubusercontent.com/4109582/60593887-007e8600-9da4-11e9-9a07-dd61ac5566c6.JPG)
![2](https://user-images.githubusercontent.com/4109582/60593889-007e8600-9da4-11e9-98d5-9160735f01e9.JPG)

**Comment by wms2** [comment]
The problem is that the printer is not recognized by the java runtime.

Maybe you have to define the printer properly in the operating system or give it some flavour that it is detected correctly.

If you find a solution, please post it. Or reopen the issue to search for more ideas.
