### ISSUE TITLE
WebService access

### ISSUE THREAD

**Issue by janosz78** [wms2/mywms#4]
Hello,
I compiled and started myWMS server. Los-Mobile works OK but I can't connect to the webservice. I used path from your documentation. I receive "404 - Not found" error when I open http://mywms.mydomain.com:8080/webservice/ManageItemDataWSBean?wsdl. Could you help me with this problem?

Best regards,
Michal Januszewski

**Comment by janosz78** [comment]
I found problem. Now it's working.

**Comment by djerman** [comment]
what was the problem?

**Comment by janosz78** [comment]
I added dependency in \dev\project-ear\pom.xml:
        <dependency>
            <groupId>de.wms2.mywms</groupId>
            <artifactId>los.ws-ejb</artifactId>
            <version>${project.version}</version>
			<type>ejb</type>
        </dependency>

I removed "safetyStock" from propOrder in \dev\los.ws-ejb\src\main\java\de\linogistix\los\inventory\ws\manage_itemdata\UpdateItemDataRequest.java.

**Comment by djerman** [comment]
Thanks

нед, 7. јун 2020. 08.44 janosz78 <notifications@github.com> је написао/ла:
